# Amount of money the server account starts with
server_starting_balance: 25000

# Amount of money the server account generates everyday
server_daily_inflation: 100

# How often to reward non-afk players (in ticks)
handout_timer: 72000

# perms as: lonelyeconomy.wages.<wageGroupName>
wages:
    citizen: 1
    regular: 1.5
    veteran: 2
    flower: 2
    whovian: 2
    vip: 3
    platinum: 5    

database: 
    prefix: le2_
    hostname: localhost
    port: 3306
    database: lonelyeconomy
    username: lonelyeconomy
    password: lonelyeconomy
    
# Attempt to transfer balances from a v1 database (dropped in the plugin folder already)
transfer_balances: false